"""Deterministic, safely-owned GitHub Pages caller-workflow support."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re


WORKFLOW_RELATIVE_PATH = Path(".github/workflows/dockit-pages.yml")
MANAGED_MARKER = "# DocKit managed workflow: github-pages v1"
_PIN = re.compile(
    r"^\s*uses:\s*ikelaiah/dockit-fp/\.github/workflows/publish-docs\.yml@"
    r"(?P<version>v[0-9][0-9A-Za-z._-]*)\s*$",
    re.MULTILINE,
)
_REQUIRED_TEXT = (
    "# Generated by DocKit.",
    "push:",
    "workflow_dispatch:",
    "github.event.repository.default_branch",
    "versioned: false",
    "release: latest",
    "contents: read",
    "pages: write",
    "id-token: write",
)


@dataclass(frozen=True)
class WorkflowInspection:
    state: str
    version: str | None = None


def render_workflow(version: str) -> str:
    """Return the complete maintained caller workflow for one DocKit release."""
    return f"""{MANAGED_MARKER}
# Generated by DocKit. Update with `dockit-fp github-pages --update`.
name: DocKit Pages

on:
  push:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  documentation:
    if: github.ref == format('refs/heads/{{0}}', github.event.repository.default_branch)
    uses: ikelaiah/dockit-fp/.github/workflows/publish-docs.yml@{version}
    with:
      versioned: false
      release: latest
    permissions:
      contents: read
      pages: write
      id-token: write
"""


def inspect_workflow(path: Path, version: str) -> WorkflowInspection:
    """Classify only a workflow at DocKit's reserved, predictable path."""
    # The command's root is resolved first, so these are the only mutable path
    # components between it and the managed filename. Refuse indirection rather
    # than allowing --update to follow a repository-controlled symlink.
    if any(candidate.is_symlink() for candidate in (path.parent.parent, path.parent, path)):
        return WorkflowInspection("unsafe")
    if not path.exists():
        return WorkflowInspection("absent")
    text = path.read_text(encoding="utf-8", errors="replace")
    if MANAGED_MARKER not in text:
        return WorkflowInspection("unmanaged")
    pin = _PIN.search(text)
    if pin is None or not all(item in text for item in _REQUIRED_TEXT):
        return WorkflowInspection("malformed")
    found_version = pin.group("version")
    if text == render_workflow(version):
        return WorkflowInspection("current", found_version)
    return WorkflowInspection("outdated", found_version)
