name: Deploy documentation

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  documentation:
    uses: ./.github/workflows/publish-docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write
